@TodoApi_HostAddress = https://localhost:5001\hello

@username = mvpdemo
# password here for demo purposes only, store these in a secret store instead of here
@password = MyP@ssw0rd

# 1: Create a user

# @name create
POST {{TodoApi_HostAddress}}/users
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

# 2: login and save the response as "login"
# @name login
POST {{TodoApi_HostAddress}}/users/token
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

GET https://httpbin.org/headers
X-Custom: {{login.response.headers.Server}}


###

# 3: Put the bearer token into a variable
#@authtoken = {{login.response.body.$.token}}
###
# 4: Get todos and verify there is none
GET {{TodoApi_HostAddress}}/todos
Authorization: Bearer {{login.response.body.$.token}}

###

# 5: Create a couple TODO items
# @name todo1
POST {{TodoApi_HostAddress}}/todos
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
  "title": "Do MVP Demo"
}
### 


# @name todo2
POST {{TodoApi_HostAddress}}/todos
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
  "title": "Try API with an HTTP file"
}

###

# 6: Get todos and verify there are two
GET {{TodoApi_HostAddress}}/todos
Authorization: Bearer {{login.response.body.$.token}}

###

# 7: Get the first TODO we created by id
GET {{TodoApi_HostAddress}}/todos/{{todo1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.token}}
###

# 8: Modify the first TODO title
PUT {{TodoApi_HostAddress}}/todos/{{todo1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
    "id": {{todo1.response.body.$.id}},
    "title":"{{todo1.response.body.$.title}} - verified at {{$datetime rfc1123}}"
}
###
# 9: Verify the title was updated
GET {{TodoApi_HostAddress}}/todos/{{todo1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.token}}
###

# 10: Mark first TODO as complete
PUT {{TodoApi_HostAddress}}/todos/{{todo1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.token}}
Content-Type: application/json

{
    "id": {{todo1.response.body.$.id}},
    "title": "{{todo1.response.body.$.title}}",
    "isComplete": true
}

###

# 11: Delete the first todo we created
DELETE {{TodoApi_HostAddress}}/todos/{{todo1.response.body.$.id}}
Authorization: Bearer {{login.response.body.$.token}}

###

# 12: Verify only 1 todo left
GET {{TodoApi_HostAddress}}/todos
Authorization: Bearer {{login.response.body.$.token}}

###


# @name initialRequest
GET https://httpbin.org/headers
X-CUSTOM: SomeHeaderHere
###

GET https://httpbin.org/headers
X-PrevValue: {{initialRequest.response.}}

###


### Basic Auth Request to httpbin.org
# @name httpbinlogin
GET https://httpbin.org/basic-auth/myusername/mypassword
Authorization: Basic bXl1c2VybmFtZTpteXBhc3N3b3Jk

###

GET https://httpbin.org/headers
X-SERVER: {{httpbinlogin.response.headers.Server}}

###

GET https://httpbin.org/headers
X-Username: {{httpbinlogin.response.body.$.user}}

###

# @name binHeader
GET https://httpbin.org/headers

###

GET https://httpbin.org/headers

###

